version: "3.9"
services:
  postgres:
    hostname: postgres
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=accounting
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
networks:
  postgres:
    driver: bridge